# Generated by Django 2.2 on 2020-08-30 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20200830_1949'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
