# Generated by Django 2.2 on 2020-08-30 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_name',
        ),
    ]
