# Generated by Django 2.2 on 2020-08-30 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20200831_0050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='p_n',
        ),
        migrations.AddField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
