# Generated by Django 2.2 on 2020-08-30 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20200831_0109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='p_n',
            new_name='product_name',
        ),
    ]
